# Generated by Django 4.2.3 on 2023-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name="profile",
            name="dues",
            field=models.FloatField(default=1.0),
        ),
    ]
