# Generated by Django 4.2.3 on 2023-07-31 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_requests"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Requests",
        ),
    ]
