# Generated by Django 4.2.3 on 2023-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_delete_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="default.jpg", upload_to="media/profile_pictures/"
            ),
        ),
    ]
