# Generated by Django 4.2.4 on 2023-08-02 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_friendrequests"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendRequests",
        ),
    ]
