# Generated by Django 4.2.4 on 2023-08-05 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_delete_friendrequests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendlist",
            name="friend_name",
        ),
    ]
