# Generated by Django 4.2.4 on 2023-08-06 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_friendlist_friend_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendList",
        ),
    ]
