# Generated by Django 4.2.4 on 2023-08-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("smartsplit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(default="", max_length=100)),
                ("message", models.CharField(default="", max_length=100)),
                ("recipient", models.CharField(default="", max_length=100)),
                ("accept_status", models.BooleanField(default=False)),
                ("send_status", models.BooleanField(default=False)),
                ("reject_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FriendList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friend_username", models.CharField(default="", max_length=100)),
                ("friend_name", models.CharField(default="", max_length=100)),
                (
                    "foreign_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
