# Generated by Django 4.2.3 on 2023-07-31 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smartsplit", "0002_rename_req_amnt_requests_reqest_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requests",
            old_name="reqest_amount",
            new_name="request_amount",
        ),
    ]
