# Generated by Django 4.2.4 on 2023-08-02 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smartsplit", "0002_friendrequests_friendlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendList",
        ),
    ]
