# Generated by Django 4.2.4 on 2023-08-02 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smartsplit", "0003_delete_friendlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FriendRequests",
        ),
    ]
