# Generated by Django 4.2.4 on 2023-08-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartsplit", "0006_remove_friendrequests_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequests",
            name="accept_status",
        ),
        migrations.RemoveField(
            model_name="friendrequests",
            name="reject_status",
        ),
        migrations.AddField(
            model_name="friendrequests",
            name="status",
            field=models.CharField(default="pending", max_length=30),
        ),
    ]
