# Generated by Django 4.2.4 on 2023-08-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartsplit", "0007_remove_friendrequests_accept_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequests",
            name="friend_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="friendrequests",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
